spring:
  datasource:
    url: jdbc:h2:mem:test;INIT=RUNSCRIPT FROM 'classpath:ddl.sql'\;RUNSCRIPT FROM 'classpath:data.sql'
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      show_sql: true
      format_sql: true
      cache:
        use_query_cache: true
        use_second_level_cache: true
        region.factory_class: jcache
        provider: org.ehcache.jsr107.EhcacheCachingProvider
      javax:
        cache:
          missing_cache_strategy: create