# demo config

server:
  port: 8080

keyStore:
  path: demo-keystore.jceks
  type: jceks
  password: demo

dataBase:
  url: jdbc:h2:mem:test;INIT=RUNSCRIPT FROM 'classpath:ddl.sql'\;RUNSCRIPT FROM 'classpath:data.sql'
  driverClass: org.h2.Driver
  dialect: org.hibernate.dialect.H2Dialect
  properties:
    hibernate.show_sql: true
    hibernate.format_sql: true
    hibernate.current_session_context_class: thread
    hibernate.cache.use_query_cache: true
    hibernate.cache.use_second_level_cache: true
    hibernate.cache.region.factory_class: jcache
    hibernate.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
    hibernate.javax.cache.missing_cache_strategy: create
